version: "3"
services:
  app_react:
    build: ./frontend
    container_name: app_react
    volumes:
      - build_react:/var/www/html
    env_file:
      - ./frontend/.env
    depends_on:
      - app_node

  app_node:
    build: ./backend
    container_name: app_node
    ports:
      - 5000:5000
    env_file:
      - ./node/.env
    volumes:
      - ./node:/usr/src
      - /usr/src/node_modules
    entrypoint: dockerize -wait tcp://banco:5432 -timeout 20s docker-entrypoint.sh
    command: "npm run start"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: db
    env_file:
      - ./backend/.env
    ports:
      - 2345:${POSTGRES_PORT}
    restart: always
    volumes:
      - volume_banco:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - app_react
      - app_node
